### ISSUE TITLE
Readme betterment for new users

### ISSUE THREAD

**Issue by emilykok** [wearefrank/frank-gateway#29]
I had been given the task by Jeroen as an outsider to check the readme for how well it was usable for new users. From this I have a few possible areas for improvement as advice:

- The Apache/apisix docker page is missing in the main readme + instructions on how to utilize it.
- It is unclear how to utilize it, only understanding it when Jeroen clarified how it functioned.
- Readme is focussed on Linux sub systems. It might be useful to add that bit of information and other prerequisites to the readme.
- Might be handy to link to the other readme's. From the demo I understood there were demo setups, where could those be found?
- Maybe also link the demo presentation
- A starters guide on what Apache/apisix is in the scope of the project so clarify some points for total beginners. (an explanation just like in the live demo should suffice.)

**Comment by pimg** [comment]
Thanks for the feedback, I cleaned up and improved the documentation based on your feedback in this PR: https://github.com/ibissource/frank-api-gateway/pull/30

**Comment by pimg** [comment]
fixed in #30
